server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: school-service
          uri: lb:http://SCHOOL-SERVICE
          predicates:
            - Path=/api/v1/schools/**
        - id: student-service
          uri: lb:http://STUDENT-SERVICE
          predicates:
            - Path=/api/v1/students/**

management:
  tracing:
    sampling:
      probability: 1.0